import type {Metadata} from "next";
import {Bebas_Neue} from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import {ConvexClientProvider} from "@/components/ConvexClientProvider";
import Navbar from "@/components/Navbar";
import SyncUserWithConvex from "@/components/SyncUserWithConvex";
import {Toaster} from "@/components/ui/sonner";

const bebasNeue = Bebas_Neue({
    weight: '400',
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${bebasNeue.className} antialiased min-h-[100vh]`}>
        <ConvexClientProvider>
            <ClerkProvider>
                <Navbar/>
                <SyncUserWithConvex/>
                <div className="container mx-auto">
                    {children}
                </div>
                <Toaster />
            </ClerkProvider>
        </ConvexClientProvider>
        </body>
        </html>
    );
}
